import type {
  User,
  Task,
  TaskCategory,
  Reward,
  Achievement,
  Challenge,
  UserChallenge,
  Character,
  CalendarEvent,
} from './types';

export const characters: Character[] = [
  { id: '1', name: 'Guerrero', avatar: '⚔️', unlocked: true },
  { id: '2', name: 'Mago', avatar: '🧙‍♂️', unlocked: false, cost: 500 },
  { id: '3', name: 'Ninja', avatar: '🥷', unlocked: false, cost: 750 },
  { id: '4', name: 'Dragón', avatar: '🐉', unlocked: false, cost: 1000 },
];

export const mockUser: User = {
  id: '1',
  name: 'Alex Gamer',
  email: 'alex@gamifi.app',
  level: 12,
  totalXP: 2450,
  coins: 1250,
  streak: 7,
  avatar: '🎮',
  character: characters[0],
  skills: {
    physical: { level: 8, currentXP: 150, totalXP: 950, xpToNextLevel: 200 },
    wisdom: { level: 6, currentXP: 80, totalXP: 680, xpToNextLevel: 150 },
    mental: { level: 10, currentXP: 50, totalXP: 1250, xpToNextLevel: 250 },
    social: { level: 5, currentXP: 120, totalXP: 520, xpToNextLevel: 130 },
    creativity: { level: 7, currentXP: 90, totalXP: 790, xpToNextLevel: 180 },
    discipline: { level: 9, currentXP: 180, totalXP: 1080, xpToNextLevel: 220 },
  },
};

export const taskCategories: TaskCategory[] = [
  {
    id: 'physical',
    name: 'Físico',
    icon: '💪',
    color: 'bg-red-500',
    description: 'Ejercicio, deporte y actividad física',
    primarySkill: 'physical',
    subcategories: ['Cardio', 'Fuerza', 'Flexibilidad', 'Deportes', 'Caminar'],
  },
  {
    id: 'wisdom',
    name: 'Sabiduría',
    icon: '📚',
    color: 'bg-blue-500',
    description: 'Aprendizaje, lectura y conocimiento',
    primarySkill: 'wisdom',
    subcategories: ['Lectura', 'Cursos', 'Documentales', 'Investigación', 'Idiomas'],
  },
  {
    id: 'mental',
    name: 'Mental',
    icon: '🧠',
    color: 'bg-purple-500',
    description: 'Concentración, memoria y agilidad mental',
    primarySkill: 'mental',
    subcategories: ['Meditación', 'Puzzles', 'Matemáticas', 'Programación', 'Estrategia'],
  },
  {
    id: 'social',
    name: 'Social',
    icon: '👥',
    color: 'bg-green-500',
    description: 'Relaciones interpersonales y comunicación',
    primarySkill: 'social',
    subcategories: ['Familia', 'Amigos', 'Networking', 'Voluntariado', 'Presentaciones'],
  },
  {
    id: 'creativity',
    name: 'Creatividad',
    icon: '🎨',
    color: 'bg-yellow-500',
    description: 'Arte, música y expresión creativa',
    primarySkill: 'creativity',
    subcategories: ['Dibujo', 'Música', 'Escritura', 'Fotografía', 'Manualidades'],
  },
  {
    id: 'discipline',
    name: 'Disciplina',
    icon: '🎯',
    color: 'bg-gray-600',
    description: 'Organización, productividad y hábitos',
    primarySkill: 'discipline',
    subcategories: ['Trabajo', 'Limpieza', 'Finanzas', 'Planificación', 'Rutinas'],
  },
];

export const mockTasks: Task[] = [
  {
    id: '1',
    title: 'Hacer 30 minutos de ejercicio',
    description: 'Cualquier actividad física: caminar, correr, gym, yoga',
    category: taskCategories[0],
    subcategory: 'Cardio',
    difficulty: 'medium',
    skillRewards: { physical: 50 },
    coinReward: 5,
    completed: false,
    recurring: true,
    recurringType: 'daily',
    estimatedDuration: 30,
  },
  {
    id: '2',
    title: 'Beber 2L de agua',
    description: 'Mantener hidratación durante el día',
    category: taskCategories[0],
    subcategory: 'Salud',
    difficulty: 'easy',
    skillRewards: { physical: 20 },
    coinReward: 2,
    completed: false,
    recurring: true,
    recurringType: 'daily',
    estimatedDuration: 0,
  },
  {
    id: '3',
    title: 'Dormir 8 horas',
    description: 'Descanso completo para recuperación',
    category: taskCategories[0],
    subcategory: 'Descanso',
    difficulty: 'medium',
    skillRewards: { physical: 50, mental: 30 },
    coinReward: 8,
    completed: false,
    recurring: true,
    recurringType: 'daily',
    estimatedDuration: 480,
  },
  {
    id: '4',
    title: 'No tomar alcohol',
    description: 'Mantener sobriedad por un día más',
    category: taskCategories[0],
    subcategory: 'Autocontrol',
    difficulty: 'hard',
    skillRewards: { physical: 30, mental: 20 },
    coinReward: 5,
    completed: false,
    recurring: true,
    recurringType: 'daily',
    estimatedDuration: 0,
  },
  {
    id: '5',
    title: 'No pedir delivery',
    description: 'Preparar y comer en casa sin pedir comida afuera',
    category: taskCategories[0],
    subcategory: 'Alimentación',
    difficulty: 'medium',
    skillRewards: { physical: 20, creativity: 20 },
    coinReward: 4,
    completed: false,
    recurring: true,
    recurringType: 'daily',
    estimatedDuration: 60,
  },
  {
    id: '6',
    title: 'No comer pan',
    description: 'Evitar pan durante el día como reto nutricional',
    category: taskCategories[0],
    subcategory: 'Alimentación',
    difficulty: 'medium',
    skillRewards: { physical: 30, mental: 10 },
    coinReward: 4,
    completed: false,
    recurring: true,
    recurringType: 'daily',
    estimatedDuration: 0,
  },
  {
    id: '7',
    title: 'Ir al gimnasio o jugar tenis / salir a caminar o correr',
    description: 'Elegir alguna actividad física de mayor intensidad',
    category: taskCategories[0],
    subcategory: 'Cardio / Deporte',
    difficulty: 'medium',
    skillRewards: { physical: 50 },
    coinReward: 5,
    completed: false,
    recurring: true,
    recurringType: 'daily',
    estimatedDuration: 60,
  },
  {
    id: '8',
    title: 'Leer 20 páginas',
    description: 'Continuar con el libro actual',
    category: taskCategories[1],
    subcategory: 'Lectura',
    difficulty: 'easy',
    skillRewards: { wisdom: 40 },
    coinReward: 4,
    completed: false,
    recurring: true,
    recurringType: 'daily',
    estimatedDuration: 25,
  },
  {
    id: '9',
    title: 'Meditar 15 minutos',
    description: 'Práctica de mindfulness y relajación',
    category: taskCategories[2],
    subcategory: 'Mindfulness',
    difficulty: 'easy',
    skillRewards: { mental: 35 },
    coinReward: 3,
    completed: false,
    recurring: true,
    recurringType: 'daily',
    estimatedDuration: 15,
  },
  {
    id: '10',
    title: 'Dedicar 30 minutos a mi proyecto de música',
    description: 'Componer, grabar, practicar o producir',
    category: taskCategories[4],
    subcategory: 'Música',
    difficulty: 'medium',
    skillRewards: { creativity: 40 },
    coinReward: 4,
    completed: false,
    recurring: true,
    recurringType: 'daily',
    estimatedDuration: 30,
  },
  {
    id: '11',
    title: 'Escribir un párrafo creativo',
    description: 'Poema, cuento corto, reflexión personal',
    category: taskCategories[4],
    subcategory: 'Escritura',
    difficulty: 'medium',
    skillRewards: { creativity: 35, wisdom: 15 },
    coinReward: 5,
    completed: false,
    recurring: true,
    recurringType: 'daily',
    estimatedDuration: 20,
  },
  {
    id: '12',
    title: 'Planificar mi semana',
    description: 'Organizar tareas personales y laborales',
    category: taskCategories[2],
    subcategory: 'Planeamiento',
    difficulty: 'medium',
    skillRewards: { mental: 40 },
    coinReward: 4,
    completed: false,
    recurring: true,
    recurringType: 'weekly',
    estimatedDuration: 30,
  },
];

export const mockRewards: Reward[] = [
  {
    id: '1',
    title: 'Personaje Mago',
    description: 'Desbloquea el poderoso personaje Mago',
    cost: 500,
    type: 'character',
    category: 'character',
    icon: '🧙‍♂️',
    available: true,
    claimed: false,
    rarity: 'rare',
  },
  {
    id: '2',
    title: 'Café Premium',
    description: 'Disfruta de tu café favorito sin culpa',
    cost: 100,
    type: 'external',
    category: 'food',
    icon: '☕',
    available: true,
    claimed: false,
    rarity: 'common',
  },
  {
    id: '3',
    title: 'Corona Dorada',
    description: 'Accesorio épico para tu avatar',
    cost: 300,
    type: 'cosmetic',
    category: 'accessory',
    icon: '👑',
    available: true,
    claimed: false,
    rarity: 'epic',
  },
  {
    id: '4',
    title: 'Videojuego Nuevo',
    description: 'Ese juego que tanto querías',
    cost: 800,
    type: 'external',
    category: 'entertainment',
    icon: '🎮',
    available: true,
    claimed: false,
    rarity: 'legendary',
  },
  {
    id: '5',
    title: 'Día de Descanso',
    description: 'Un día libre de tareas opcionales',
    cost: 200,
    type: 'internal',
    category: 'break',
    icon: '🛋️',
    available: true,
    claimed: false,
    rarity: 'common',
  },
];

export const mockCalendarEvents: CalendarEvent[] = [
  {
    id: '1',
    taskId: '1',
    date: new Date(),
    completed: false,
    type: 'recurring',
  },
  {
    id: '2',
    taskId: '2',
    date: new Date(),
    completed: false,
    type: 'recurring',
  },
];

export const mockAchievements: Achievement[] = [
  {
    id: '1',
    title: 'Primeros Pasos',
    description: 'Completa tu primera tarea',
    icon: '👣',
    unlocked: true,
    unlockedAt: new Date(),
    requirement: 'Completar 1 tarea',
  },
  {
    id: '2',
    title: 'Racha de 7 días',
    description: 'Mantén una racha de 7 días completando tareas',
    icon: '🔥',
    unlocked: false,
    requirement: 'Mantener una racha de 7 días',
  },
  {
    id: '3',
    title: 'Nivel 5 en Físico',
    description: 'Alcanza el nivel 5 en la habilidad Físico',
    icon: '💪',
    unlocked: false,
    requirement: 'Alcanzar nivel 5 en Físico',
    skillRequirement: { physical: 5 },
  },
  {
    id: '4',
    title: 'Maestro del Saber',
    description: 'Alcanza el nivel 10 en Sabiduría',
    icon: '📚',
    unlocked: false,
    requirement: 'Alcanzar nivel 10 en Sabiduría',
    skillRequirement: { wisdom: 10 },
  },
  {
    id: '5',
    title: 'Social Butterfly',
    description: 'Alcanza el nivel 5 en Social',
    icon: '👥',
    unlocked: false,
    requirement: 'Alcanzar nivel 5 en Social',
    skillRequirement: { social: 5 },
  },
  {
    id: '6',
    title: 'Productivo',
    description: 'Completa 10 tareas en total',
    icon: '✅',
    unlocked: false,
    requirement: 'Completar 10 tareas',
  },
  {
    id: '7',
    title: 'Súper Productivo',
    description: 'Completa 50 tareas en total',
    icon: '🚀',
    unlocked: false,
    requirement: 'Completar 50 tareas',
  },
  {
    id: '8',
    title: 'Máquina de Productividad',
    description: 'Completa 100 tareas en total',
    icon: '⚡',
    unlocked: false,
    requirement: 'Completar 100 tareas',
  },
  {
    id: '9',
    title: 'Veterano',
    description: 'Alcanza el nivel 10',
    icon: '🏅',
    unlocked: false,
    requirement: 'Alcanzar nivel 10',
  },
  {
    id: '10',
    title: 'Leyenda',
    description: 'Alcanza el nivel 25',
    icon: '👑',
    unlocked: false,
    requirement: 'Alcanzar nivel 25',
  },
  {
    id: '11',
    title: 'Desafiante',
    description: 'Completa 5 challenges',
    icon: '🏆',
    unlocked: false,
    requirement: 'Completar 5 challenges',
  },
  {
    id: '12',
    title: 'Rico',
    description: 'Acumula 1000 monedas',
    icon: '💰',
    unlocked: false,
    requirement: 'Ganar 1000 monedas',
  },
  {
    id: '13',
    title: 'Imparable',
    description: 'Mantén una racha de 30 días',
    icon: '🔥',
    unlocked: false,
    requirement: 'Mantener una racha de 30 días',
  },
  {
    id: '14',
    title: 'Equilibrado',
    description: 'Completa tareas de todas las categorías en un día',
    icon: '⚖️',
    unlocked: false,
    requirement: 'Completar todas las categorías en un día',
  },
];

export const mockChallenges: Challenge[] = [
  {
    id: '1',
    title: 'Guerrero Diario',
    description: 'Completa 5 tareas en un solo día',
    icon: '⚔️',
    type: 'daily',
    difficulty: 'medium',
    xpReward: 100,
    coinReward: 50,
    requirements: {
      type: 'daily',
      tasksToComplete: 5,
    },
    active: true,
    featured: true,
    rarity: 'common',
    category: 'productivity',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '2',
    title: 'Racha Imparable',
    description: 'Mantén una racha de 7 días consecutivos',
    icon: '🔥',
    type: 'weekly',
    difficulty: 'hard',
    xpReward: 300,
    coinReward: 150,
    requirements: {
      type: 'streak',
      streakDays: 7,
    },
    active: true,
    featured: true,
    rarity: 'rare',
    category: 'consistency',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '3',
    title: 'Maestro Físico',
    description: 'Alcanza el nivel 10 en habilidad Física',
    icon: '💪',
    type: 'skill',
    difficulty: 'epic',
    xpReward: 500,
    coinReward: 300,
    requirements: {
      type: 'skill',
      skillType: 'physical',
      skillLevel: 10,
    },
    active: true,
    featured: false,
    rarity: 'epic',
    category: 'fitness',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '4',
    title: 'Equilibrio Total',
    description: 'Completa tareas de todas las 6 categorías en una semana',
    icon: '⚖️',
    type: 'diversity',
    difficulty: 'hard',
    xpReward: 250,
    coinReward: 125,
    requirements: {
      type: 'diversity',
      categoriesRequired: ['physical', 'wisdom', 'mental', 'social', 'creativity', 'discipline'],
    },
    active: true,
    featured: true,
    rarity: 'rare',
    category: 'balance',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '5',
    title: 'Desafío de Fin de Año',
    description: 'Evento especial: Completa 50 tareas antes del 31 de diciembre',
    icon: '🎊',
    type: 'temporal',
    difficulty: 'epic',
    xpReward: 1000,
    coinReward: 500,
    requirements: {
      type: 'temporal',
      tasksToComplete: 50,
      deadline: new Date('2024-12-31'),
    },
    startDate: new Date('2024-12-01'),
    endDate: new Date('2024-12-31'),
    active: true,
    featured: true,
    rarity: 'legendary',
    category: 'event',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const mockUserChallenges: UserChallenge[] = [
  {
    id: '1',
    userId: '1',
    challengeId: '1',
    progress: 3,
    target: 5,
    completed: false,
    progressData: {
      tasksCompletedToday: 3,
      lastUpdated: new Date(),
    },
    challenge: mockChallenges[0],
  },
  {
    id: '2',
    userId: '1',
    challengeId: '2',
    progress: 4,
    target: 7,
    completed: false,
    progressData: {
      currentStreak: 4,
      lastCompletionDate: new Date(),
    },
    challenge: mockChallenges[1],
  },
  {
    id: '3',
    userId: '1',
    challengeId: '4',
    progress: 4,
    target: 6,
    completed: false,
    progressData: {
      categoriesCompleted: ['physical', 'wisdom', 'mental', 'creativity'],
      weekStartDate: new Date(),
    },
    challenge: mockChallenges[3],
  },
];
